spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=manojgavhane1812@gmail.com
spring.mail.password=sghp mohh twuz huqo


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true